env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - standard-with-typescript
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: "./tsconfig.json"
plugins:
  - react
  - prettier
rules:
  {
    "prettier/prettier": ["error", { "endOfLine": "auto" }],
    "@typescript-eslint/restrict-template-expressions": ["off"],
    "@typescript-eslint/no-unused-vars": ["warn"],
    "react/react-in-jsx-scope": ["off"],
    "@typescript-eslint/triple-slash-reference": ["off"],
  }
ignorePatterns: ["*stories.tsx"]
settings:
  react: { version: detect }
