import { Filter } from 'models/db/filter/Filter';
import React, { useState } from 'react';

/**
 * @type T is an autogenerated db_FieldName type
 * @type U is an autogenerated db_Record type
 */
export interface iDynamicMultiSelect<T, U> {
  /** provide the api call that will fetch filtered db records */
  getFilteredRecordApi: (filter: Filter<T>) => Promise<U[]>;
  /** db Field Name you want to search on */
  searchOn: T;
  /** db Record field that corresponds to user input */
  selectInputOn: keyof U;
  /** list of all db Record fields that you want to the result to display as */
  displayResultsOn: Array<keyof U>;
  label?: string;
  placeholder?: string;
}

const getSelectedPills = <U,>(
  selectedRecords: Set<U>,
  displayResultsOn: Array<keyof U>
): JSX.Element[] => {
  const pills = new Array<JSX.Element>();
  selectedRecords.forEach((record) => {
    const displayVal = displayResultsOn
      .map((field) => record[field] as string)
      .join(', ');
    pills.push(
      // Probs should create a custom class for pill (with an X icon to get rid of pill from list)
      <div className='badge-accent badge m-1 p-4' key={displayVal}>
        {displayVal}
      </div>
    );
  });

  return pills;
};

export const DynamicMultiSelect = <T, U>(
  props: iDynamicMultiSelect<T, U>
): JSX.Element => {
  const [searchRes, setSearchRes] = useState(new Array<U>());
  const [userInput, setUserInput] = useState('');
  const [selectedRecords, setSelectedRecords] = useState<Set<U>>(new Set());

  const onInputChange = (val: React.ChangeEvent<HTMLInputElement>): void => {
    setUserInput(val.target.value);
    const filter: Filter<T> = {
      filters: [[[props.searchOn, { Like: val.target.value }]]],
      orderBy: [],
    };
    props
      .getFilteredRecordApi(filter)
      .then((res) => {
        setSearchRes(res);
      })
      .catch((err) => err);
  };

  return (
    <>
      {props.label === undefined ? (
        <></> // Don't show label if undefined
      ) : (
        <label className='label'>
          <span className='label-text'>{props.label}</span>
        </label>
      )}
      <div className='dropdown w-full max-w-md'>
        <input
          type='text'
          placeholder={props.placeholder}
          className='input-bordered input w-full max-w-xs'
          onChange={onInputChange}
          value={userInput}
        />
        {searchRes.length === 0 ? (
          <></> // Don't show list if no results
        ) : (
          <ul className='dropdown-content menu rounded-box mt-2 mb-2 w-52  overflow-auto bg-base-100 p-2 shadow'>
            {searchRes.map((record, idx) => {
              return (
                <li
                  key={`${record}-${idx}`}
                  tabIndex={0}
                  onClick={() => {
                    setUserInput('');
                    setSelectedRecords(selectedRecords.add(record));
                    setSearchRes([]);
                  }}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') {
                      setUserInput('');
                      setSelectedRecords(selectedRecords.add(record));
                      setSearchRes([]);
                    }
                  }}
                >
                  <a>
                    {props.displayResultsOn
                      .map((field) => record[field] as string)
                      .join(', ')}
                  </a>
                </li>
              );
            })}
          </ul>
        )}
      </div>
      <div className='max-w-xs p-2'>
        {getSelectedPills(selectedRecords, props.displayResultsOn)}
      </div>
    </>
  );
};
