// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface db_Allele {
  name: string;
  contents: string | null;
  sysGeneName: string | null;
  variationName: string | null;
}
