// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface db_Condition { name: string, description: string | null, maleMating: bigint | null, lethal: boolean | null, femaleSterile: boolean | null, arrested: boolean | null, maturationDays: number | null, }