// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface db_ExpressionRelation {
  alleleName: string;
  expressingPhenotypeName: string;
  expressingPhenotypeWild: boolean;
  alteringPhenotypeName: string | null;
  alteringPhenotypeWild: boolean | null;
  alteringCondition: string | null;
  isSuppressing: boolean;
}
