// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterKeyValue } from './db_FilterKeyValue';

export interface FilterInfo {
  filters: FilterKeyValue[];
  orderBy: string | null;
}
