// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface db_StrainAllele {
  strainName: string;
  alleleName: string;
  isOnTop: boolean;
  isOnBot: boolean;
}
