// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface db_StrainAllele {
  strain_name: string;
  allele_name: string;
  is_on_top: boolean;
  is_on_bot: boolean;
}
