// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from './db_Task';

export interface db_Task {
  id: bigint;
  due_date: string | null;
  action: Action;
  strain1: string;
  strain2: string | null;
  notes: string | null;
  completed: boolean;
  tree_id: bigint;
}
