// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chromosome } from "./filter/db_ChromosomeEnum";

export interface db_VariationInfo { alleleName: string, chromosome: Chromosome | null, physLoc: bigint | null, geneticLoc: number | null, }