// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chromosome } from './filter/db_ChromosomeEnum';

export interface db_Variation {
  alleleName: string;
  chromosome: Chromosome | null;
  physLoc: number | null;
  geneticLoc: number | null;
  recombSuppressor: [number, number] | null;
}
