// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface db_VariationInfo { alleleName: string, chromosome: string | null, physLoc: bigint | null, geneticLoc: number | null, }