// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlleleFieldName } from './db_AlleleFieldName';
import type { SpecialFilter } from './db_SpecialFilter';

export interface AlleleFilter {
  fieldFilters: Record<AlleleFieldName, string[]>;
  fieldRanges: Record<AlleleFieldName, SpecialFilter[]>;
  orderBy: AlleleFieldName[];
}
