// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { SpecialFilter } from 'models/db/filter/db_SpecialFilter';
import type { AlleleFieldName } from './db_AlleleFieldName';

export interface AlleleFilter {
  fieldFilters: Map<AlleleFieldName, string[]>;
  fieldSpecialFilters: Map<AlleleFieldName, SpecialFilter[]>;
  orderBy: AlleleFieldName[];
}
