// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { SpecialFilter } from 'models/db/filter/db_SpecialFilter';
import type { AlleleExpressionFieldName } from './db_AlleleExpressionFieldName';

export interface AlleleExpressionFilter {
  fieldFilters: Map<AlleleExpressionFieldName, string[]>;
  fieldSpecialFilters: Map<AlleleExpressionFieldName, SpecialFilter[]>;
  orderBy: AlleleExpressionFieldName[];
}
