// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlleleFieldName } from './db_AlleleFieldName';
import type { FilterRange } from './db_FilterRange';

export interface AlleleFilter {
  fieldFilters: Record<AlleleFieldName, string[]>;
  fieldRanges: Record<AlleleFieldName, FilterRange[]>;
  orderBy: AlleleFieldName[];
}
