// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlleleExpressionFieldName } from './db_AlleleExpressionFieldName';
import type { SpecialFilter } from './db_SpecialFilter';

export interface AlleleExpressionFilter {
  fieldFilters: Record<AlleleExpressionFieldName, string[]>;
  fieldSpecialFilters: Record<AlleleExpressionFieldName, SpecialFilter[]>;
  orderBy: AlleleExpressionFieldName[];
}
