// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlleleExpressionFieldName } from './db_AlleleExpressionFieldName';
import type { FilterRange } from './db_FilterRange';

export interface AlleleExpressionFilter {
  fieldFilters: Record<AlleleExpressionFieldName, string[]>;
  fieldRanges: Record<AlleleExpressionFieldName, FilterRange[]>;
  orderBy: AlleleExpressionFieldName[];
}
