// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConditionFieldName } from './db_ConditionFieldName';
import type { FilterRange } from './db_FilterRange';

export interface ConditionFilter {
  fieldFilters: Record<ConditionFieldName, string[]>;
  fieldRanges: Record<ConditionFieldName, FilterRange[]>;
  orderBy: ConditionFieldName[];
}
