// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConditionFieldName } from './db_ConditionFieldName';
import type { SpecialFilter } from './db_SpecialFilter';

export interface ConditionFilter {
  fieldFilters: Record<ConditionFieldName, string[]>;
  fieldSpecialFilters: Record<ConditionFieldName, SpecialFilter[]>;
  orderBy: ConditionFieldName[];
}
