// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { SpecialFilter } from 'models/db/filter/db_SpecialFilter';
import type { ConditionFieldName } from './db_ConditionFieldName';

export interface ConditionFilter {
  fieldFilters: Map<ConditionFieldName, string[]>;
  fieldSpecialFilters: Map<ConditionFieldName, SpecialFilter[]>;
  orderBy: ConditionFieldName[];
}
