// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConditionFieldName = "Name" | "Description" | "MaleMating" | "Lethal" | "FemaleSterile" | "Arrested" | "MaturationDays";