// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExpressionRelationFieldName =
  | 'AlleleName'
  | 'ExpressingPhenotypeName'
  | 'ExpressingPhenotypeWild'
  | 'AlteringPhenotypeName'
  | 'AlteringPhenotypeWild'
  | 'AlteringCondition'
  | 'IsSuppressing';
