// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { SpecialFilter } from 'models/db/filter/db_SpecialFilter';
import type { ExpressionRelationFieldName } from './db_ExpressionRelationFieldName';

export interface ExpressionRelationFilter {
  fieldFilters: Map<ExpressionRelationFieldName, string[]>;
  fieldSpecialFilters: Map<ExpressionRelationFieldName, SpecialFilter[]>;
  orderBy: ExpressionRelationFieldName[];
}
