// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExpressionRelationFieldName } from './db_ExpressionRelationFieldName';
import type { SpecialFilter } from './db_SpecialFilter';

export interface ExpressionRelationFilter {
  fieldFilters: Record<ExpressionRelationFieldName, string[]>;
  fieldSpecialFilters: Record<ExpressionRelationFieldName, SpecialFilter[]>;
  orderBy: ExpressionRelationFieldName[];
}
