// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExpressionRelationFieldName } from './db_ExpressionRelationFieldName';
import type { FilterRange } from './db_FilterRange';

export interface ExpressionRelationFilter {
  fieldFilters: Record<ExpressionRelationFieldName, string[]>;
  fieldRanges: Record<ExpressionRelationFieldName, FilterRange[]>;
  orderBy: ExpressionRelationFieldName[];
}
