// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FieldName =
  | 'AlleleName'
  | 'ExpressingPhenotypeName'
  | 'ExpressingPhenotypeWild'
  | 'Dominance'
  | 'Name'
  | 'Contents'
  | 'GeneName'
  | 'VariatinName'
  | 'MaleMating'
  | 'Lethal'
  | 'FemaleSterile'
  | 'Arrested'
  | 'MaturationDays'
  | 'AlteringPhenotypeName'
  | 'AlteringPhenotypeWild'
  | 'IsSuppressing'
  | 'PhysLoc'
  | 'GeneticLoc'
  | 'Wild'
  | 'ShortName'
  | 'Description';
