// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldName } from './db_FieldName';
import type { FilterRange } from './db_FilterRange';

export interface FilterInfo {
  fieldFilters: Record<FieldName, string[]>;
  fieldRanges: Record<FieldName, FilterRange[]>;
  orderBy: FieldName[];
}
