// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RangeType } from './db_RangeType';

export interface FilterRange {
  fieldValue: string;
  rangeType: RangeType;
}
