// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeneFieldName } from './db_GeneFieldName';
import type { SpecialFilter } from './db_SpecialFilter';

export interface GeneFilter {
  fieldFilters: Record<GeneFieldName, string[]>;
  fieldRanges: Record<GeneFieldName, SpecialFilter[]>;
  orderBy: GeneFieldName[];
}
