// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterRange } from './db_FilterRange';
import type { GeneFieldName } from './db_GeneFieldName';

export interface GeneFilter {
  fieldFilters: Record<GeneFieldName, string[]>;
  fieldRanges: Record<GeneFieldName, FilterRange[]>;
  orderBy: GeneFieldName[];
}
