// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterRange } from './db_FilterRange';
import type { PhenotypeFieldName } from './db_PhenotypeFieldName';

export interface PhenotypeFilter {
  fieldFilters: Record<PhenotypeFieldName, string[]>;
  fieldRanges: Record<PhenotypeFieldName, FilterRange[]>;
  orderBy: PhenotypeFieldName[];
}
