// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PhenotypeFieldName } from './db_PhenotypeFieldName';
import type { SpecialFilter } from './db_SpecialFilter';

export interface PhenotypeFilter {
  fieldFilters: Record<PhenotypeFieldName, string[]>;
  fieldSpecialFilters: Record<PhenotypeFieldName, SpecialFilter[]>;
  orderBy: PhenotypeFieldName[];
}
