// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpecialFilterType } from "./db_SpecialFilterType";

export interface SpecialFilter { fieldValue: string, specialFilterType: SpecialFilterType, }