// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { SpecialFilter } from 'models/db/filter/db_SpecialFilter';
import type { VariationFieldName } from './db_VariationFieldName';

export interface VariationInfoFilter {
  fieldFilters: Map<VariationFieldName, string[]>;
  fieldSpecialFilters: Map<VariationFieldName, SpecialFilter[]>;
  orderBy: VariationFieldName[];
}
