// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpecialFilter } from './db_SpecialFilter';
import type { VariationFieldName } from './db_VariationFieldName';

export interface VariationInfoFilter {
  fieldFilters: Record<VariationFieldName, string[]>;
  fieldSpecialFilters: Record<VariationFieldName, SpecialFilter[]>;
  orderBy: VariationFieldName[];
}
