import { db_Error } from 'models/db/db_Error';
import { FilterType } from 'models/db/filter/FilterType';
import { isDbError } from 'models/error';

export type FilterTuple<T> = [T, FilterType];
/**
 * A generic filter for interacting with the database
 * The type you provide should be an autogenerated DB field name enum
 *
 */
export interface Filter<T> {
  /**
   * @overview Specify dynamic filtering of a DB table
   *
   * @description The nested array structure allows AND / OR statements
   * To create chained AND statements: add tuples in the INNER-MOST arrays
   * To create chained OR statements: add multiple arrays with a single tuple in each
   * To create mixed AND / OR statements: any combination of the above 2 lines
   *
   * -----------------------------------------------
   *
   * @example
   * [
   *   [ [field1, val1], [field2, val2], [field3, val3] ]
   * ]
   *
   * ^ would generate: WHERE (field1 == val1 AND field2 == val2 AND field3 == val3);
   *
   * -----------------------------------------------
   *
   * @example
   * [
   *   [ [field1, val1] ],
   *   [ [field1, val2] ],
   *   [ [field2, val3] ],
   * ]
   *
   * ^ would generate: WHERE (field1 == val1) OR (field1 == val2) OR (field2 == val3);
   *
   * -----------------------------------------------
   *
   * @example
   * [
   *   [ [field1, val1], [field2, val2], [field3, val3] ],
   *   [ [field1, val1], [field4, val4] ],
   *   [ [field5, val5] ],
   * ]
   *
   * ^ would generate: WHERE (field1 == val1 AND field2 == val2 AND field3 == and val3) OR
   *                         (field1 == val1 AND field4 == val4) OR
   *                         (field5 == val5);
   */
  filters: Array<Array<FilterTuple<T>>>;
  /**
   * @overview Allows ordering based on fieldNames
   * @example
   * [field1, field2] would generate the the following statement:
   *
   * <select query> ... ORDER BY field1, field2;
   */
  orderBy: T[];
}

/**
 * Representation for backend booleean type
 */
type dbBool = 'True' | 'False';

/**
 * @param val frontend boolean
 * @returns backend boolean conversion
 */
export const getDbBoolean = (val: boolean): dbBool => {
  return val ? 'True' : 'False';
};

/**
 * Given an array of db records (or db_Error), returns the first element
 * @param T type of the db_table you are querying
 * @param response response from tauri db invokation
 * @param error optional error message you would like to display if there are no records
 * @returns
 */
export const getSingleRecordOrError = <T>(
  response: T[] | db_Error,
  error = 'unable to get a single record from db'
): T | db_Error => {
  if (isDbError(response)) return response; // already db_error
  if (response.length > 0) return response[0];

  return { SqlQueryError: error }; // no records, return db_error
};
