import { SpecialFilter } from 'models/db/filter/db_SpecialFilter';

/**
 * A generic filter for interacting with the database
 * The type you provide should be an autogenerated DB field name enum
 * */
export interface Filter<T> {
  fieldFilters: Map<T, string[]>;
  fieldSpecialFilters: Map<T, SpecialFilter[]>;
  orderBy: T[];
}
