// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FilterType =
  | { Range: [string, boolean, string, boolean] }
  | { LessThan: [string, boolean] }
  | { GreaterThan: [string, boolean] }
  | { Equal: string }
  | { NotEqual: string }
  | { Like: string }
  | 'Null'
  | 'NotNull'
  | 'True'
  | 'False';
