#[cfg(test)]
pub mod testdata {
    use crate::models::{condition::Condition, gene::Gene, phenotype::Phenotype};

    pub fn get_genes() -> Vec<Gene> {
        vec![
            Gene {
                name: "dpy-10".to_string(),
                chromosome: Some("II".to_string()),
                phys_loc: Some(6710149),
                gen_loc: Some(0.0),
            },
            Gene {
                name: "lin-15B".to_string(),
                chromosome: Some("X".to_string()),
                phys_loc: Some(15726123),
                gen_loc: Some(22.95),
            },
            Gene {
                name: "ox1059".to_string(),
                chromosome: Some("IV".to_string()),
                phys_loc: Some(11425742),
                gen_loc: Some(4.98),
            },
            Gene {
                name: "unc-119".to_string(),
                chromosome: Some("III".to_string()),
                phys_loc: Some(10902641),
                gen_loc: Some(5.59),
            },
            Gene {
                name: "unc-18".to_string(),
                chromosome: Some("X".to_string()),
                phys_loc: Some(7682896),
                gen_loc: Some(-1.35),
            },
        ]
    }

    pub fn get_conditions() -> Vec<Condition> {
        vec![
            Condition {
                name: "15C".to_string(),
                description: None,
                male_mating: Some(3),
                lethal: Some(false),
                female_sterile: Some(false),
                arrested: Some(false),
                maturation_days: Some(4.0),
            },
            Condition {
                name: "25C".to_string(),
                description: None,
                male_mating: Some(3),
                lethal: Some(false),
                female_sterile: Some(false),
                arrested: Some(false),
                maturation_days: Some(3.0),
            },
            Condition {
                name: "Histamine".to_string(),
                description: None,
                male_mating: Some(3),
                lethal: Some(false),
                female_sterile: Some(false),
                arrested: Some(false),
                maturation_days: Some(3.0),
            },
            Condition {
                name: "Tetracycline".to_string(),
                description: None,
                male_mating: Some(3),
                lethal: Some(false),
                female_sterile: Some(false),
                arrested: Some(false),
                maturation_days: Some(3.0),
            },
        ]
    }

    pub fn get_phenotypes() -> Vec<Phenotype> {
        vec![
            Phenotype {
                name: "Flp".to_string(),
                wild: true,
                short_name: "Flp(+)".to_string(),
                description: None,
                male_mating: Some(3),
                lethal: Some(false),
                female_sterile: Some(false),
                arrested: Some(false),
                maturation_days: Some(3.0),
            },
            Phenotype {
                name: "GFP".to_string(),
                wild: false,
                short_name: "GFP".to_string(),
                description: None,
                male_mating: Some(3),
                lethal: Some(false),
                female_sterile: Some(false),
                arrested: Some(false),
                maturation_days: Some(3.0),
            },
            Phenotype {
                name: "GFP(GABA)".to_string(),
                wild: false,
                short_name: "GFP(GABA)".to_string(),
                description: None,
                male_mating: Some(3),
                lethal: Some(false),
                female_sterile: Some(false),
                arrested: Some(false),
                maturation_days: Some(3.0),
            },
            Phenotype {
                name: "GFP-NLS".to_string(),
                wild: false,
                short_name: "GFP-NLS".to_string(),
                description: None,
                male_mating: Some(3),
                lethal: Some(false),
                female_sterile: Some(false),
                arrested: Some(false),
                maturation_days: Some(3.0),
            },
            Phenotype {
                name: "HygR".to_string(),
                wild: false,
                short_name: "HygR".to_string(),
                description: None,
                male_mating: Some(3),
                lethal: Some(false),
                female_sterile: Some(false),
                arrested: Some(false),
                maturation_days: Some(3.0),
            },
            Phenotype {
                name: "NeoR".to_string(),
                wild: false,
                short_name: "NeoR".to_string(),
                description: None,
                male_mating: Some(3),
                lethal: Some(false),
                female_sterile: Some(false),
                arrested: Some(false),
                maturation_days: Some(3.0),
            },
            Phenotype {
                name: "YFP(pharynx)".to_string(),
                wild: false,
                short_name: "YFP(pharynx)".to_string(),
                description: None,
                male_mating: Some(3),
                lethal: Some(false),
                female_sterile: Some(false),
                arrested: Some(false),
                maturation_days: Some(3.0),
            },
            Phenotype {
                name: "YFP-NLS".to_string(),
                wild: false,
                short_name: "YFP-NLS".to_string(),
                description: None,
                male_mating: Some(3),
                lethal: Some(false),
                female_sterile: Some(false),
                arrested: Some(false),
                maturation_days: Some(3.0),
            },
            Phenotype {
                name: "dpy-10".to_string(),
                wild: false,
                short_name: "dpy".to_string(),
                description: None,
                male_mating: Some(0),
                lethal: Some(false),
                female_sterile: Some(false),
                arrested: Some(false),
                maturation_days: Some(4.0),
            },
            Phenotype {
                name: "lethal".to_string(),
                wild: false,
                short_name: "lethal".to_string(),
                description: None,
                male_mating: Some(0),
                lethal: Some(true),
                female_sterile: Some(false),
                arrested: Some(false),
                maturation_days: None,
            },
            Phenotype {
                name: "lin-15A".to_string(),
                wild: false,
                short_name: "muv".to_string(),
                description: None,
                male_mating: Some(3),
                lethal: Some(false),
                female_sterile: Some(false),
                arrested: Some(false),
                maturation_days: Some(3.0),
            },
            Phenotype {
                name: "lin-15A".to_string(),
                wild: true,
                short_name: "muv".to_string(),
                description: None,
                male_mating: Some(3),
                lethal: Some(false),
                female_sterile: Some(false),
                arrested: Some(false),
                maturation_days: Some(3.0),
            },
            Phenotype {
                name: "lin-15B".to_string(),
                wild: false,
                short_name: "muv".to_string(),
                description: None,
                male_mating: None,
                lethal: None,
                female_sterile: None,
                arrested: None,
                maturation_days: None,
            },
            Phenotype {
                name: "lin-15B".to_string(),
                wild: true,
                short_name: "muv".to_string(),
                description: None,
                male_mating: None,
                lethal: None,
                female_sterile: None,
                arrested: None,
                maturation_days: None,
            },
            Phenotype {
                name: "mCherry".to_string(),
                wild: false,
                short_name: "mCherry".to_string(),
                description: None,
                male_mating: Some(3),
                lethal: Some(false),
                female_sterile: Some(false),
                arrested: Some(false),
                maturation_days: Some(3.0),
            },
            Phenotype {
                name: "mScarlet(coel)".to_string(),
                wild: false,
                short_name: "mScarlet(coel)".to_string(),
                description: None,
                male_mating: Some(3),
                lethal: Some(false),
                female_sterile: Some(false),
                arrested: Some(false),
                maturation_days: Some(3.0),
            },
            Phenotype {
                name: "mec-3".to_string(),
                wild: false,
                short_name: "mec".to_string(),
                description: None,
                male_mating: None,
                lethal: None,
                female_sterile: None,
                arrested: None,
                maturation_days: None,
            },
            Phenotype {
                name: "paralyzed".to_string(),
                wild: false,
                short_name: "paralyzed".to_string(),
                description: None,
                male_mating: Some(0),
                lethal: Some(false),
                female_sterile: Some(false),
                arrested: Some(false),
                maturation_days: None,
            },
            Phenotype {
                name: "rol".to_string(),
                wild: false,
                short_name: "rol".to_string(),
                description: None,
                male_mating: Some(0),
                lethal: Some(false),
                female_sterile: Some(false),
                arrested: Some(false),
                maturation_days: Some(3.0),
            },
            Phenotype {
                name: "unc-119".to_string(),
                wild: false,
                short_name: "unc".to_string(),
                description: None,
                male_mating: Some(0),
                lethal: Some(false),
                female_sterile: Some(false),
                arrested: Some(false),
                maturation_days: Some(4.0),
            },
            Phenotype {
                name: "unc-119".to_string(),
                wild: true,
                short_name: "unc".to_string(),
                description: None,
                male_mating: None,
                lethal: None,
                female_sterile: None,
                arrested: None,
                maturation_days: None,
            },
            Phenotype {
                name: "unc-18".to_string(),
                wild: false,
                short_name: "unc".to_string(),
                description: None,
                male_mating: Some(1),
                lethal: Some(false),
                female_sterile: Some(false),
                arrested: Some(false),
                maturation_days: Some(4.0),
            },
            Phenotype {
                name: "unc-18".to_string(),
                wild: true,
                short_name: "unc".to_string(),
                description: None,
                male_mating: None,
                lethal: None,
                female_sterile: None,
                arrested: None,
                maturation_days: None,
            },
            Phenotype {
                name: "unc-31".to_string(),
                wild: false,
                short_name: "unc".to_string(),
                description: None,
                male_mating: None,
                lethal: None,
                female_sterile: None,
                arrested: None,
                maturation_days: None,
            },
            Phenotype {
                name: "unc-5".to_string(),
                wild: false,
                short_name: "unc".to_string(),
                description: None,
                male_mating: Some(0),
                lethal: Some(false),
                female_sterile: Some(false),
                arrested: Some(false),
                maturation_days: Some(4.0),
            },
        ]
    }
}
