#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Testing backend"
npm run test-back

echo "Testing frontend"
npm run test-front

echo "Running lint"
npx eslint "src/**/*.{js,jsx,ts,tsx}" --fix
git add src/models/db/*
cd src-tauri && cargo clippy